name: Update Archive

on:
  schedule:
    # UTC 10:39 & 18:39
    # 北京 18:39 & 02:39
    - cron: '39 10,18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fetch Updates from API
        run: node scripts/update-archive.mjs
        env:
          API_ENDPOINT: ${{ vars.API_ENDPOINT }}
      - name: Commit Updates to Github
        if: success()
        env:
          USER_NAME: ${{ vars.USER_NAME }}
          USER_EMAIL: ${{ vars.USER_EMAIL }}
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git status --short
          git add ./archive
          git commit --allow-empty -m "ci: update archive $(date --iso-8601=seconds)"
          git push
